jump-dev/AmplNLWriter.jl

- src/AmplNLWriter.jl
> Use .sol file to determine whether to read in a solution

- examples/jump_maxmin.jl
- src/nl_params.jl
- test/runtests.jl
See https://github.com/JackDunnNZ/AmplNLWriter.jl/issues/15.
> Allow min() and max() functions

- src/AmplNLWriter.jl
- src/nl_write.jl
- test/nl_write.jl
- test/runtests.jl
Realized I'd done this a while back...
> Use randomly named files for reading and writing. Closes #10

- src/AmplNLWriter.jl
@kibaekkim, could you check if this works for you with minotaur? It reads in the .sol file you linked, but just want to make sure.
Fixes #33
> Fix .sol reader logic to match AMPL's implementation

- examples/jump_nltrig.jl
- test/REQUIRE
Don't merge until JuMP 0.12 is tagged
> Fix re-solving test for JuMP 0.12

- examples/jump_nlexpr.jl
- src/nl_linearity.jl
- test/REQUIRE
- test/runtests.jl
Don't merge until JuMP 0.12 is tagged
---
@anriseth This fixes #29 for me, can you confirm?
> Fix error with NLExpr in JuMP 0.12. Closes #29

- src/AmplNLWriter.jl
- src/deprecated.jl
@JackDunnNZ does this seem alright?
> Remove broken deprecation

- examples/jump_pruning.jl
- src/AmplNLWriter.jl
- src/nl_write.jl
Ref https://github.com/JuliaOpt/AmplNLWriter.jl/issues/39#issuecomment-237339527 and JuliaOpt/JuMP.jl#820
cc @mlubin your example should work now
> Support constraints that have no variables

- src/AmplNLWriter.jl
Any reason this wasn't done before?
> precompile the module

- .travis.yml
- REQUIRE
- appveyor.yml
- src/AmplNLWriter.jl
Okay, I was sufficiently annoyed to fix the deprecation warnings.
> deprecation fix and drop julia 0.4

- src/AmplNLWriter.jl
- src/nl_write.jl
- test/nl_convert.jl
> Adding a better error message for user defined functions

- .travis.yml
Turns out Jullia v0.6 was working, on linux at least...
> Various touchups to Travis Build

- src/AmplNLWriter.jl
These changes should (?) fix the package on Julia nightly and make the test output slightly nicer.
> Misc fixes to v0.4.0

- Project.toml
- src/MOI_wrapper.jl
- test/MINLPTests/Project.toml
- test/MINLPTests/run_minlptests.jl
- test/MOI_wrapper.jl
Fix #97
Please be kind. I don't really know what I'm doing.
Just tried to adapt similar PR as suggested in the issue https://github.com/JuliaOpt/AmplNLWriter.jl/issues/97#issuecomment-601610479
> One can adapt the PR of odow/PATH.jl#5 to this package to make it work.
> Make model <: MOI.AbstractOptimizer

- src/AmplNLWriter.jl
Well. I now know far more about NL files. And they're even more complicated than I had previously thought. 
I'm surprised that no one complained before @muriloasouza. But then again, you need a fairly specific set-up in order to reproduce this. 
@ccoffrin could this be the source of your "I think there's a bug in AmplNLWriter but I don't know where or how to reproduce hunch?"
Closes #79.
> Fix ordering of nonlinear variables

- src/MOI_wrapper.jl
This way the user can access MPBModel, and access information therein (e.g., solve_time).
> Put mpb model in Model.ext

- src/AmplNLWriter.jl
> Throw nicer error message when expression graphs not given

- src/AmplNLWriter.jl
- test/MINLPTests/run_minlptests.jl
- test/MOI_wrapper.jl
> Implement MOI.RawParameter

- src/AmplNLWriter.jl
- test/MINLPTests/run_minlptests.jl
- test/MOI_wrapper.jl
- test/ipopt.opt
> Implement MOI.ConstraintDual

- src/NLExpr.jl
- test/MINLPTests/run_minlptests.jl
- test/NLModel.jl
> Add a rewrite rule for left-division

- src/AmplNLWriter.jl
- test/MOI_wrapper.jl
> Allow redirecting solver IO

- Project.toml
- src/AmplNLWriter.jl
- test/MOI_wrapper.jl
> Implement MOI.SolveTime

- src/AmplNLWriter.jl
- test/MOI_wrapper.jl
> Add directory argument

- Project.toml
- src/AmplNLWriter.jl
https://github.com/jump-dev/AmplNLWriter.jl/pull/171 but without the changes to MINLPTests, which can wait until new JuMP is released.
> Add support for MOI.ScalarNonlinearFunction

- test/MINLPTests/run_minlptests.jl
- test/MOI_wrapper.jl
x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2423
> Exclude more integrality tests

- README.md
> Clarify that Bonmin and Couenne do not work on Apple aarch64
