jump-dev/AmplNLWriter.jl

- README.md
- src/AmplNLWriter.jl
- src/nl_write.jl
An extension of #14. Using the ASL implementation as a guide, this reads the `.sol` file properly, allowing us to extract the status of the solve correctly without resorting to string matching.
It also makes available the following variables, named as per AMPL:
- `solve_result`: one of `solved`, `solved?`, `infeasible`, `unbounded`, `limit`, `failure`
- `solve_result_num`: the numeric code returned by the solver. This is solver-specific and gives more granularity than `solve_result`
- `solve_message`: the message printed by the solver at termination
- `solve_exitcode`: the exitcode of the solve process
As a result of figuring out the way to request suffixes in the `.sol` file, the solvers are now called in a standardized way, and so the `pre_command` and `post_command` business has been …
> [WIP] Create and read .sol file correctly to get solve status

- REQUIRE
- src/AmplNLWriter.jl
Ref #22 and https://github.com/JuliaOpt/MathProgBase.jl/pull/91
Can't merge until CoinOptServices updates to support MPB 0.4 otherwise tests break.
@mlubin It's pretty simple, but the macro to generate the wrapper functions seems a bit hacky. Any ideas for a better way?
It passes tests locally after fixing the conflicts with CoinOptServices re. supporting MPB 0.4.
> Updates for MPB 0.4

- README.md
- src/AmplNLWriter.jl
- src/deprecated.jl
- test/runtests.jl
Ref #26, this changes the options to use a vector of strings so that options that aren't `key=value` can be specified, in particular, the path to the `scip.set` options file for `scipampl`.
This also adds to the readme some instructions about how to use the options with the COIN-OR solvers and SCIP (as well as some info on setting SCIP up, ref JuliaOpt/JuMP.jl#588)
> Use string array for options

- src/AmplNLWriter.jl
It's useful for benchmarking purposes to be able to isolate the time spent in the solver as opposed to any overhead from the AmplNLWriter package itself.
> implement MathProgBase.getsolvetime

- src/AmplNLWriter.jl
I think this is preferable to returning a vector of length 0 for ``getsolutuion`` in the ``:Error`` case, which can cause JuMP to crash.
> return NaN solution on solver error

- src/nl_write.jl
> Only iterate over present variables when writing linear constraints

- src/AmplNLWriter.jl
Fixes #51, the objective value calculation is near instant for that example now.
We still have to fallback to the old `eval` behavior in case of an error since there are some functions like `min`/`max` that are supported by .nl but not by the JuMP NLPEvaluator
> Use NLPEvaluator to get objective value where possible

- .codecov.yml
- .travis.yml
- README.md
- REQUIRE
- appveyor.yml
- examples/jump_const_obj.jl
- examples/jump_maxmin.jl
- examples/jump_minlp.jl
- examples/jump_nlexpr.jl
- examples/jump_nltrig.jl
- examples/jump_no_obj.jl
- examples/jump_nonlinearbinary.jl
- examples/jump_pruning.jl
- src/AmplNLWriter.jl
- src/nl_convert.jl
- src/nl_linearity.jl
- src/nl_write.jl
- test/REQUIRE
- test/nl_convert.jl
- test/nl_linearity.jl
- test/nl_write.jl
- test/runtests.jl
*This PR should probably be split into some smaller ones*
I'm playing around with the NL file-format interface to NEOS (ref https://neos-server.org/neos/solvers/milp:CPLEX/NL.html and https://github.com/odow/NEOS.jl/issues/17).
I made some changes so I can read the .sol file from a stream instead of having to write the file to disk.
I've also removed CoinOptServices from the testing suite as it needs some work and was causing failures on my windows machine.
I've removed `BonminNLSolver`, `CouenneNLSolver`, and `IpoptNLSolver` (and therefore the conditional dependencies) in favour of forcing the user to explicitly construct the solvers.
```julia
using AmplNLWriter
solver = IpoptNLSolver()
```
becomes
```julia
using AmplNLWriter, Ipopt
solver = AmplNLSolver(Ipopt.amplexe)
```
which is a bit …
> Revamp for Julia v0.6

- examples/jump_minlp.jl
- examples/jump_nonlinearbinary.jl
- src/AmplNLWriter.jl
- test/runtests.jl
- test/sol_file_parser.jl
As found by @bgulcan, here is an offending `.sol` file returned by Couenne that `AmplNLWriter.jl` cannot parse. The problem is that it starts with an empty line. To simplify things, this PR just returns all lines prior to `Options` concatenated together as the solver message. Since this is solver-specific and intended for the user, this doesn't seem like a bad thing to do.
```
Couenne (/home/bgulcan/.julia/v0.6/AmplNLWriter/.solverdata/tmpMSxFvq.nl Mar  6 2018): Infeasible
Options
3
0
1
0
140
0
110
0
objno 0 220
```
Closes #80
> Fix bug in sol file parser if the file begins with empty lines.

- .travis.yml
- REQUIRE
- src/AmplNLWriter.jl
- src/MOI_wrapper.jl
- test/MINLPTests/Manifest.toml
- test/MINLPTests/Project.toml
- test/MINLPTests/run_minlptests.jl
- test/MOI_wrapper.jl
- test/runtests.jl
This PR wraps the MathProgBase nonlinear interface to AmplNLWriter. It provides `AmplNLWriter.Optimizer` with the same arguments as `AmplNLSolver`. 
<s>
Requires 
</s> 
Tests are now done using an MINLPTests.jl build stage on Travis.
cc @ccoffrin 
(Looking at certain unnamed people, please don't comment on how hacky this is.)
> Add an MOI wrapper

- src/AmplNLWriter.jl
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
A common issue seems to be the solver erroring at some point. Let's try-catch, throw a nicer error message, and make it available via `RawStatusString`.
Closes #92 
Closes #78
> Add better error handling and msg for run cmd errors

- README.md
> Update Ipopt ampl path

- src/AmplNLWriter.jl
The way the solver is invoked currently makes the solver impossible to access stdin.
This PR is solving this issue.
> added stdin in the solver invocation

- Project.toml
- test/MINLPTests/Project.toml
I recently released `ASL_jll@0.1.2`, which appeared to break `Ipopt_jll@3.13.2`. Let's see if `ASL_jll@0.1.2` works with `Ipopt_jll@3.13.4`.
I'll probably need to go and edit the compat of Ipopt_jll.
> Relax restriction on Ipopt_jll

- Project.toml
- src/AmplNLWriter.jl
- test/MOI_wrapper.jl
This makes it possible for a package like [NEOS.jl](https://github.com/odow/NEOS.jl) to leverage the
AmplNLWriter infrastructure by providing a new AbstractSolverCommand.
Here it is: https://github.com/odow/NEOS.jl/pull/30
```Julia
julia> using JuMP, NEOS
julia> model = Model() do
NEOS.Optimizer(
email="<my personal email redacted>", 
solver="CPLEX",
)
end
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: AmplNLWriter
julia> @variable(model, 0 <= x <= 4)
x
julia> @NLobjective(model, Min, (x-1)^2 + 1)
julia> optimize!(model)
Job 10393923 dispatched
password: jMuWANEz
---------- Begin Solver Output -----------
Condor submit: 'neos.submit'
Condor submit: 'watchdog.submit'
Job submitted to NEOS HTCondor pool.
julia> …
```
> Refactor how the solver is called.

- src/AmplNLWriter.jl
From https://discourse.julialang.org/t/amplnlwriter-no-longer-works-with-jump/70740/2
Things were currently working because
```Julia
julia> options = Dict{String,Any}()
Dict{String, Any}()
julia> [isempty(v) ? k : "$(k)=$(v)" for (k, v) in options]
String[]
``` 
But maybe this doesn't hold on every Julia version or machine type. Anyway, we shouldn't be relying on inference to determine this correctly.
Closes #147
> Fix empty options

- LICENSE.md
- src/AmplNLWriter.jl
- test/MINLPTests/run_minlptests.jl
- test/MOI_wrapper.jl
- test/runtests.jl
cc @JackDunnNZ 
We discussed this on today's monthly developer call. I'm going to go through and unify our licenses. Where multiple people have contributed, I'm changing the copyright to "Package contributors" since the copyright isn't owned by the original individual. In cases where there are only 1 or 2 contributors, the named individuals can stay.
> Add copyright headers

- Project.toml
- src/AmplNLWriter.jl
- test/MINLPTests/Project.toml
- test/MOI_wrapper.jl
> Fix libblastrampoline with Ipopt_jll

- src/AmplNLWriter.jl
- test/MOI_wrapper.jl
> Improve error for missing sol file

- src/AmplNLWriter.jl
- test/MOI_wrapper.jl
Closes #196 
The `Cmd` wraps things in `' '`, but this happens to the entire `'output_file=/path/to/file.txt'`, and the binary fails to parse that.
> Fix writing options that contain spaces
